CREATE TABLE IF NOT EXISTS public.chatbot_conversations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text,
  session_id text unique,
  car_id bigint references public.cars(id) on delete set null,
  conversation_type text default 'general' check (conversation_type in ('search', 'report', 'help', 'faq', 'general')),
  status text default 'active' check (status in ('active', 'closed', 'archived')),
  last_message_at timestamp with time zone,
  message_count integer default 0,
  resolved boolean default false
);

CREATE TABLE IF NOT EXISTS public.chatbot_messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  conversation_id bigint references public.chatbot_conversations(id) on delete cascade not null,
  sender_type text check (sender_type in ('user', 'bot')) not null,
  message_text text not null,
  message_type text default 'text' check (message_type in ('text', 'suggestion', 'action', 'info')),
  intent text,
  entities jsonb,
  confidence float,
  is_escalated boolean default false,
  assigned_agent_email text
);

CREATE TABLE IF NOT EXISTS public.chatbot_intents (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  intent_name text unique not null,
  description text,
  sample_phrases text[] not null,
  response_type text default 'template' check (response_type in ('template', 'search', 'action')),
  response_template text,
  action_type text,
  is_active boolean default true
);

CREATE TABLE IF NOT EXISTS public.chatbot_training_data (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  conversation_id bigint references public.chatbot_conversations(id) on delete cascade,
  user_input text not null,
  bot_response text not null,
  user_feedback text check (user_feedback in ('helpful', 'unhelpful', 'incorrect')),
  suggested_improvement text,
  is_useful boolean default false
);

CREATE TABLE IF NOT EXISTS public.chatbot_faqs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  question text not null,
  answer text not null,
  category text,
  views integer default 0,
  helpful_count integer default 0,
  unhelpful_count integer default 0,
  is_active boolean default true
);

ALTER TABLE public.chatbot_conversations enable row level security;
ALTER TABLE public.chatbot_messages enable row level security;
ALTER TABLE public.chatbot_intents enable row level security;
ALTER TABLE public.chatbot_training_data enable row level security;
ALTER TABLE public.chatbot_faqs enable row level security;

CREATE POLICY "Users can view their conversations"
ON public.chatbot_conversations for select
USING (user_email = auth.jwt() ->> 'email' OR true);

CREATE POLICY "Users can insert conversation"
ON public.chatbot_conversations for insert
WITH CHECK (true);

CREATE POLICY "Users can view messages"
ON public.chatbot_messages for select
USING (true);

CREATE POLICY "Users can insert message"
ON public.chatbot_messages for insert
WITH CHECK (true);

CREATE POLICY "Everyone can view intents"
ON public.chatbot_intents for select
USING (true);

CREATE POLICY "Admins can manage intents"
ON public.chatbot_intents for insert
to authenticated
WITH CHECK (true);

CREATE POLICY "Everyone can view FAQs"
ON public.chatbot_faqs for select
USING (is_active = true);

CREATE POLICY "Admins can manage FAQs"
ON public.chatbot_faqs for insert
to authenticated
WITH CHECK (true);

CREATE INDEX IF NOT EXISTS idx_chatbot_conversations_user_email ON public.chatbot_conversations(user_email);
CREATE INDEX IF NOT EXISTS idx_chatbot_conversations_session_id ON public.chatbot_conversations(session_id);
CREATE INDEX IF NOT EXISTS idx_chatbot_conversations_status ON public.chatbot_conversations(status);
CREATE INDEX IF NOT EXISTS idx_chatbot_messages_conversation_id ON public.chatbot_messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_chatbot_messages_sender_type ON public.chatbot_messages(sender_type);
CREATE INDEX IF NOT EXISTS idx_chatbot_intents_name ON public.chatbot_intents(intent_name);
CREATE INDEX IF NOT EXISTS idx_chatbot_faqs_category ON public.chatbot_faqs(category);
