-- Create conversations table
CREATE TABLE IF NOT EXISTS public.conversations (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  car_id bigint references public.cars(id) on delete cascade not null,
  user1_email text not null,
  user2_email text not null,
  last_message_at timestamp with time zone,
  last_message text,
  is_closed boolean default false
);

-- Create messages table
CREATE TABLE IF NOT EXISTS public.messages (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  conversation_id bigint references public.conversations(id) on delete cascade not null,
  sender_email text not null,
  content text not null,
  is_read boolean default false,
  read_at timestamp with time zone
);

-- Enable RLS
ALTER TABLE public.conversations ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

-- Policies for conversations
CREATE POLICY "Users can view their conversations"
ON public.conversations FOR SELECT
USING (user1_email = auth.jwt() ->> 'email' OR user2_email = auth.jwt() ->> 'email');

CREATE POLICY "Users can create conversations"
ON public.conversations FOR INSERT
WITH CHECK (user1_email = auth.jwt() ->> 'email' OR user2_email = auth.jwt() ->> 'email');

CREATE POLICY "Users can update their conversations"
ON public.conversations FOR UPDATE
USING (user1_email = auth.jwt() ->> 'email' OR user2_email = auth.jwt() ->> 'email');

-- Policies for messages
CREATE POLICY "Users can view messages in their conversations"
ON public.messages FOR SELECT
USING (
  conversation_id IN (
    SELECT id FROM conversations
    WHERE user1_email = auth.jwt() ->> 'email' OR user2_email = auth.jwt() ->> 'email'
  )
);

CREATE POLICY "Users can send messages"
ON public.messages FOR INSERT
WITH CHECK (sender_email = auth.jwt() ->> 'email');

CREATE POLICY "Users can mark messages as read"
ON public.messages FOR UPDATE
USING (
  conversation_id IN (
    SELECT id FROM conversations
    WHERE user1_email = auth.jwt() ->> 'email' OR user2_email = auth.jwt() ->> 'email'
  )
);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_conversations_user1_email ON public.conversations(user1_email);
CREATE INDEX IF NOT EXISTS idx_conversations_user2_email ON public.conversations(user2_email);
CREATE INDEX IF NOT EXISTS idx_conversations_car_id ON public.conversations(car_id);
CREATE INDEX IF NOT EXISTS idx_messages_conversation_id ON public.messages(conversation_id);
CREATE INDEX IF NOT EXISTS idx_messages_sender_email ON public.messages(sender_email);
CREATE INDEX IF NOT EXISTS idx_messages_is_read ON public.messages(is_read);
