CREATE TABLE IF NOT EXISTS public.face_recognition_profiles (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text not null unique,
  face_vector_data bytea,
  face_confidence float check (face_confidence >= 0 and face_confidence <= 1) default 0,
  is_verified boolean default false,
  verification_date timestamp with time zone,
  verification_attempts integer default 0,
  last_verification_at timestamp with time zone,
  face_encoding text,
  face_descriptor jsonb
);

CREATE TABLE IF NOT EXISTS public.face_verification_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text not null,
  verification_type text check (verification_type in ('owner_verification', 'login', 'transaction', 'booking')) default 'login',
  attempt_status text check (attempt_status in ('success', 'failed', 'pending')) default 'pending',
  confidence_score float check (confidence_score >= 0 and confidence_score <= 1),
  ip_address text,
  device_info text,
  location_info text
);

CREATE TABLE IF NOT EXISTS public.suspicious_faces (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  face_encoding text not null,
  reason text check (reason in ('suspected_fraud', 'banned_user', 'wanted', 'reported')),
  reported_by_email text,
  description text,
  image_url text,
  is_active boolean default true,
  flagged_count integer default 0
);

CREATE TABLE IF NOT EXISTS public.voice_commands (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text,
  command_text text not null,
  command_type text check (command_type in ('search', 'report', 'book', 'navigate', 'help')) default 'search',
  voice_file_url text,
  confidence_score float,
  processed_action text,
  is_successful boolean default false,
  execution_time_ms integer
);

CREATE TABLE IF NOT EXISTS public.voice_profiles (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text not null unique,
  voice_fingerprint bytea,
  voice_confidence float,
  training_samples integer default 0,
  is_trained boolean default false,
  accent text,
  language text default 'ar'
);

CREATE TABLE IF NOT EXISTS public.predictive_alerts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  car_id bigint references public.cars(id) on delete cascade,
  alert_type text check (alert_type in ('theft_risk', 'accident_risk', 'location_anomaly', 'pattern_match')) default 'theft_risk',
  risk_score float check (risk_score >= 0 and risk_score <= 100) default 0,
  prediction_reason text,
  recommended_action text,
  is_dismissed boolean default false,
  user_email text,
  created_by_model text,
  confidence_percentage float
);

CREATE TABLE IF NOT EXISTS public.prediction_model_training (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  model_name text not null,
  model_version text,
  training_date timestamp with time zone,
  accuracy_rate float,
  precision_rate float,
  recall_rate float,
  total_training_samples integer,
  last_updated timestamp with time zone
);

ALTER TABLE public.face_recognition_profiles enable row level security;
ALTER TABLE public.face_verification_logs enable row level security;
ALTER TABLE public.suspicious_faces enable row level security;
ALTER TABLE public.voice_commands enable row level security;
ALTER TABLE public.voice_profiles enable row level security;
ALTER TABLE public.predictive_alerts enable row level security;
ALTER TABLE public.prediction_model_training enable row level security;

CREATE POLICY "Users can view their own face profile"
ON public.face_recognition_profiles for select
USING (user_email = auth.jwt() ->> 'email' OR true);

CREATE POLICY "Users can insert face profile"
ON public.face_recognition_profiles for insert
WITH CHECK (true);

CREATE POLICY "Users can update their own profile"
ON public.face_recognition_profiles for update
USING (user_email = auth.jwt() ->> 'email' OR true);

CREATE POLICY "Users can view verification logs"
ON public.face_verification_logs for select
USING (user_email = auth.jwt() ->> 'email' OR true);

CREATE POLICY "System can insert verification logs"
ON public.face_verification_logs for insert
WITH CHECK (true);

CREATE POLICY "Admins can view suspicious faces"
ON public.suspicious_faces for select
USING (true);

CREATE POLICY "Users can view voice commands"
ON public.voice_commands for select
USING (user_email = auth.jwt() ->> 'email' OR true);

CREATE POLICY "Users can insert voice commands"
ON public.voice_commands for insert
WITH CHECK (true);

CREATE POLICY "Users can manage voice profile"
ON public.voice_profiles for select
USING (user_email = auth.jwt() ->> 'email' OR true);

CREATE POLICY "Users can view alerts"
ON public.predictive_alerts for select
USING (user_email = auth.jwt() ->> 'email' OR true);

CREATE INDEX IF NOT EXISTS idx_face_recognition_email ON public.face_recognition_profiles(user_email);
CREATE INDEX IF NOT EXISTS idx_face_recognition_verified ON public.face_recognition_profiles(is_verified);
CREATE INDEX IF NOT EXISTS idx_face_verification_logs_email ON public.face_verification_logs(user_email);
CREATE INDEX IF NOT EXISTS idx_face_verification_logs_status ON public.face_verification_logs(attempt_status);
CREATE INDEX IF NOT EXISTS idx_voice_commands_email ON public.voice_commands(user_email);
CREATE INDEX IF NOT EXISTS idx_voice_commands_type ON public.voice_commands(command_type);
CREATE INDEX IF NOT EXISTS idx_voice_profiles_email ON public.voice_profiles(user_email);
CREATE INDEX IF NOT EXISTS idx_predictive_alerts_car ON public.predictive_alerts(car_id);
CREATE INDEX IF NOT EXISTS idx_predictive_alerts_type ON public.predictive_alerts(alert_type);
CREATE INDEX IF NOT EXISTS idx_predictive_alerts_risk ON public.predictive_alerts(risk_score);
