-- Create user preferences table for location alerts
CREATE TABLE IF NOT EXISTS public.user_alert_preferences (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text not null,
  name text,
  location_name text not null,
  latitude float not null,
  longitude float not null,
  radius_km float default 5 check (radius_km > 0 and radius_km <= 100),
  car_make text,
  car_status text,
  is_active boolean default true,
  notify_via_email boolean default true,
  notify_via_app boolean default true,
  last_alert_sent timestamp with time zone
);

-- Create alerts log table
CREATE TABLE IF NOT EXISTS public.sent_alerts (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  car_id bigint references public.cars(id) on delete cascade,
  preference_id bigint references public.user_alert_preferences(id) on delete cascade,
  user_email text not null,
  notification_type text check (notification_type in ('email', 'app', 'both')) default 'app',
  is_delivered boolean default false,
  delivered_at timestamp with time zone
);

-- Enable RLS
ALTER TABLE public.user_alert_preferences enable row level security;
ALTER TABLE public.sent_alerts enable row level security;

-- Policies
CREATE POLICY "Users can view their own preferences" 
ON public.user_alert_preferences for select 
USING (user_email = auth.jwt() ->> 'email' OR true);

CREATE POLICY "Users can insert their own preferences" 
ON public.user_alert_preferences for insert 
WITH CHECK (true);

CREATE POLICY "Users can update their own preferences" 
ON public.user_alert_preferences for update 
USING (user_email = auth.jwt() ->> 'email' OR true);

CREATE POLICY "Users can delete their own preferences" 
ON public.user_alert_preferences for delete 
USING (user_email = auth.jwt() ->> 'email' OR true);

CREATE POLICY "Users can view their own alerts" 
ON public.sent_alerts for select 
USING (user_email = auth.jwt() ->> 'email' OR true);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_alert_preferences_email ON public.user_alert_preferences(user_email);
CREATE INDEX IF NOT EXISTS idx_alert_preferences_active ON public.user_alert_preferences(is_active);
CREATE INDEX IF NOT EXISTS idx_alert_preferences_location ON public.user_alert_preferences(latitude, longitude);
CREATE INDEX IF NOT EXISTS idx_sent_alerts_email ON public.sent_alerts(user_email);
CREATE INDEX IF NOT EXISTS idx_sent_alerts_car_id ON public.sent_alerts(car_id);
