CREATE TABLE IF NOT EXISTS public.investigators (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text not null,
  phone text,
  name text not null,
  bio text,
  specialization text check (specialization in ('theft', 'accidents', 'general', 'tracking')) default 'general',
  experience_years integer default 0,
  license_number text,
  is_verified boolean default false,
  verification_date timestamp with time zone,
  rating float default 0,
  total_cases_solved integer default 0,
  success_rate float default 0,
  hourly_rate float,
  availability boolean default true,
  image_url text,
  languages text[],
  certifications text[],
  is_active boolean default true
);

CREATE TABLE IF NOT EXISTS public.investigation_bookings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  car_id bigint references public.cars(id) on delete cascade not null,
  investigator_id bigint references public.investigators(id) on delete cascade not null,
  client_email text not null,
  client_phone text,
  status text default 'pending' check (status in ('pending', 'accepted', 'active', 'completed', 'cancelled')),
  booking_date timestamp with time zone not null,
  start_date timestamp with time zone,
  end_date timestamp with time zone,
  description text,
  estimated_cost float,
  actual_cost float,
  notes text,
  rating integer check (rating >= 1 and rating <= 5),
  review text
);

CREATE TABLE IF NOT EXISTS public.investigator_ratings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  investigator_id bigint references public.investigators(id) on delete cascade not null,
  booking_id bigint references public.investigation_bookings(id) on delete cascade,
  rater_email text,
  rating integer not null check (rating >= 1 and rating <= 5),
  feedback text,
  case_solved boolean,
  helpfulness_score integer check (helpfulness_score >= 1 and helpfulness_score <= 5)
);

CREATE TABLE IF NOT EXISTS public.investigation_cases (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  booking_id bigint references public.investigation_bookings(id) on delete cascade not null,
  car_id bigint references public.cars(id) on delete cascade not null,
  investigator_id bigint references public.investigators(id) on delete cascade not null,
  status text default 'open' check (status in ('open', 'investigating', 'solved', 'unsolved', 'closed')),
  case_number text unique,
  findings text,
  evidence_urls text[],
  last_update timestamp with time zone,
  completion_date timestamp with time zone,
  outcome text
);

ALTER TABLE public.investigators enable row level security;
ALTER TABLE public.investigation_bookings enable row level security;
ALTER TABLE public.investigator_ratings enable row level security;
ALTER TABLE public.investigation_cases enable row level security;

CREATE POLICY "Everyone can view investigators"
ON public.investigators for select
USING (true);

CREATE POLICY "Users can insert investigator"
ON public.investigators for insert
WITH CHECK (true);

CREATE POLICY "Admins can update investigator"
ON public.investigators for update
to authenticated
USING (true);

CREATE POLICY "Users can view bookings"
ON public.investigation_bookings for select
USING (true);

CREATE POLICY "Users can insert booking"
ON public.investigation_bookings for insert
WITH CHECK (true);

CREATE POLICY "Users and investigators can update booking"
ON public.investigation_bookings for update
USING (client_email = auth.jwt() ->> 'email' OR true);

CREATE POLICY "Everyone can view ratings"
ON public.investigator_ratings for select
USING (true);

CREATE POLICY "Anyone can rate investigator"
ON public.investigator_ratings for insert
WITH CHECK (true);

CREATE POLICY "Users can view cases"
ON public.investigation_cases for select
USING (true);

CREATE POLICY "Users can insert case"
ON public.investigation_cases for insert
WITH CHECK (true);

CREATE POLICY "Investigators can update cases"
ON public.investigation_cases for update
USING (true);

CREATE INDEX IF NOT EXISTS idx_investigators_email ON public.investigators(email);
CREATE INDEX IF NOT EXISTS idx_investigators_specialization ON public.investigators(specialization);
CREATE INDEX IF NOT EXISTS idx_investigation_bookings_car_id ON public.investigation_bookings(car_id);
CREATE INDEX IF NOT EXISTS idx_investigation_bookings_investigator_id ON public.investigation_bookings(investigator_id);
CREATE INDEX IF NOT EXISTS idx_investigation_bookings_status ON public.investigation_bookings(status);
CREATE INDEX IF NOT EXISTS idx_investigation_cases_booking_id ON public.investigation_cases(booking_id);
CREATE INDEX IF NOT EXISTS idx_investigation_cases_status ON public.investigation_cases(status);
