-- Media System Table
-- Stores images and videos for cars and case reports
CREATE TABLE IF NOT EXISTS public.media (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    car_id BIGINT REFERENCES public.cars(id) ON DELETE CASCADE,
    case_report_id UUID REFERENCES public.case_reports(id) ON DELETE CASCADE,
    media_type TEXT NOT NULL CHECK (media_type IN ('image', 'video', 'audio')),
    file_path TEXT NOT NULL, -- Path in Supabase Storage
    file_name TEXT NOT NULL,
    file_size BIGINT, -- Size in bytes
    mime_type TEXT, -- e.g., 'image/jpeg', 'video/mp4'
    duration INTEGER, -- Duration in seconds for videos
    uploaded_by UUID REFERENCES auth.users(id),
    is_primary BOOLEAN DEFAULT FALSE, -- Mark primary image
    description TEXT,
    metadata JSONB -- Store additional metadata like color analysis
);

-- Enable Row Level Security
ALTER TABLE public.media ENABLE ROW LEVEL SECURITY;

-- Policies for media
CREATE POLICY "Everyone can view media" 
ON public.media FOR SELECT 
USING (true);

CREATE POLICY "Authenticated users can upload media" 
ON public.media FOR INSERT 
TO authenticated 
WITH CHECK (true);

CREATE POLICY "Users can update their own media" 
ON public.media FOR UPDATE 
TO authenticated 
USING (uploaded_by = auth.uid());

CREATE POLICY "Admins can delete media" 
ON public.media FOR DELETE 
TO authenticated 
USING (true);

-- Color Analysis Table (for image search)
CREATE TABLE IF NOT EXISTS public.car_colors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    car_id BIGINT REFERENCES public.cars(id) ON DELETE CASCADE UNIQUE,
    primary_color TEXT NOT NULL,
    secondary_color TEXT,
    color_confidence FLOAT DEFAULT 0.0, -- Confidence score 0-1
    dominant_colors JSONB, -- Array of dominant colors with percentages
    last_analyzed TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()),
    analyzed_from_media_id BIGINT REFERENCES public.media(id)
);

-- Enable Row Level Security
ALTER TABLE public.car_colors ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Everyone can view car colors" 
ON public.car_colors FOR SELECT 
USING (true);

CREATE POLICY "Authenticated users can manage colors" 
ON public.car_colors FOR ALL 
TO authenticated 
USING (true);

-- Security Integration Table
-- Stores information about connected government agencies
CREATE TABLE IF NOT EXISTS public.security_agencies (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL, -- e.g., "Police Department", "Municipality"
    code TEXT UNIQUE NOT NULL, -- e.g., "PD_001"
    api_endpoint TEXT, -- URL to their API
    api_key_encrypted TEXT, -- Encrypted API key
    contact_email TEXT,
    contact_phone TEXT,
    country TEXT,
    region TEXT,
    is_active BOOLEAN DEFAULT TRUE,
    last_sync TIMESTAMP WITH TIME ZONE,
    sync_enabled BOOLEAN DEFAULT FALSE
);

-- Enable Row Level Security
ALTER TABLE public.security_agencies ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Only admins can view agencies" 
ON public.security_agencies FOR SELECT 
TO authenticated 
USING (true);

CREATE POLICY "Only admins can manage agencies" 
ON public.security_agencies FOR ALL 
TO authenticated 
USING (true);

-- Case Sharing Table
-- Track which cases are shared with which agencies
CREATE TABLE IF NOT EXISTS public.case_shares (
    id UUID DEFAULT gen_random_uuid() PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    car_id BIGINT REFERENCES public.cars(id) ON DELETE CASCADE,
    agency_id UUID REFERENCES public.security_agencies(id) ON DELETE CASCADE,
    shared_by UUID REFERENCES auth.users(id),
    status TEXT DEFAULT 'pending' CHECK (status IN ('pending', 'shared', 'acknowledged', 'rejected')),
    external_case_id TEXT, -- ID from the external agency
    shared_data JSONB, -- What data was shared
    last_updated TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable Row Level Security
ALTER TABLE public.case_shares ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Admins can manage case shares" 
ON public.case_shares FOR ALL 
TO authenticated 
USING (true);

-- Create Supabase Storage buckets
INSERT INTO storage.buckets (id, name, public) 
VALUES ('media', 'media', true)
ON CONFLICT (id) DO NOTHING;

INSERT INTO storage.buckets (id, name, public) 
VALUES ('evidence', 'evidence', true)
ON CONFLICT (id) DO NOTHING;

-- Storage policies for media bucket
CREATE POLICY "Public Access to Media" 
ON storage.objects FOR SELECT 
USING ( bucket_id = 'media' );

CREATE POLICY "Auth Upload to Media" 
ON storage.objects FOR INSERT 
TO authenticated 
WITH CHECK ( bucket_id = 'media' );

CREATE POLICY "Auth Update Media" 
ON storage.objects FOR UPDATE 
TO authenticated 
WITH CHECK ( bucket_id = 'media' );

-- Storage policies for evidence bucket (private)
CREATE POLICY "Admins Access to Evidence" 
ON storage.objects FOR SELECT 
TO authenticated 
USING ( bucket_id = 'evidence' );

CREATE POLICY "Admins Upload to Evidence" 
ON storage.objects FOR INSERT 
TO authenticated 
WITH CHECK ( bucket_id = 'evidence' );

-- Create indexes for better performance
CREATE INDEX idx_media_car_id ON public.media(car_id);
CREATE INDEX idx_media_case_report_id ON public.media(case_report_id);
CREATE INDEX idx_media_type ON public.media(media_type);
CREATE INDEX idx_car_colors_car_id ON public.car_colors(car_id);
CREATE INDEX idx_case_shares_car_id ON public.case_shares(car_id);
CREATE INDEX idx_case_shares_agency_id ON public.case_shares(agency_id);
