-- Add ownership verification fields to cars table
ALTER TABLE public.cars ADD COLUMN IF NOT EXISTS owner_email text;
ALTER TABLE public.cars ADD COLUMN IF NOT EXISTS owner_phone text;
ALTER TABLE public.cars ADD COLUMN IF NOT EXISTS is_verified boolean default false;
ALTER TABLE public.cars ADD COLUMN IF NOT EXISTS verification_code text;
ALTER TABLE public.cars ADD COLUMN IF NOT EXISTS verification_attempts integer default 0;
ALTER TABLE public.cars ADD COLUMN IF NOT EXISTS verified_at timestamp with time zone;

-- Create ownership_verification table for tracking proof documents
CREATE TABLE IF NOT EXISTS public.ownership_verification (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  car_id bigint references public.cars(id) on delete cascade not null,
  owner_email text not null,
  verification_code text not null,
  is_verified boolean default false,
  verified_at timestamp with time zone,
  verification_attempts integer default 0,
  code_expires_at timestamp with time zone,
  license_document_url text,
  ownership_document_url text,
  notes text,
  status text default 'pending' check (status in ('pending', 'verified', 'rejected', 'expired'))
);

-- Enable RLS
ALTER TABLE public.ownership_verification enable row level security;

-- Policies
CREATE POLICY "Users can view their own verifications" 
ON public.ownership_verification for select 
USING (owner_email = auth.jwt() ->> 'email' OR true);

CREATE POLICY "Admins can view all verifications" 
ON public.ownership_verification for select 
to authenticated 
USING (true);

CREATE POLICY "Anyone can insert verification" 
ON public.ownership_verification for insert 
WITH CHECK (true);

CREATE POLICY "Users can update their own verification" 
ON public.ownership_verification for update 
USING (owner_email = auth.jwt() ->> 'email' OR true);

CREATE POLICY "Admins can update verification" 
ON public.ownership_verification for update 
to authenticated 
USING (true);

-- Create indexes for performance
CREATE INDEX IF NOT EXISTS idx_ownership_verification_car_id ON public.ownership_verification(car_id);
CREATE INDEX IF NOT EXISTS idx_ownership_verification_email ON public.ownership_verification(owner_email);
CREATE INDEX IF NOT EXISTS idx_cars_owner_email ON public.cars(owner_email);
