-- Create user security settings table
CREATE TABLE IF NOT EXISTS public.user_security (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text unique not null,
  two_factor_enabled boolean default false,
  two_factor_verified boolean default false,
  two_factor_code text,
  code_expires_at timestamp with time zone,
  last_login timestamp with time zone,
  login_attempts integer default 0,
  account_locked boolean default false,
  locked_until timestamp with time zone,
  password_changed_at timestamp with time zone
);

-- Create security logs table
CREATE TABLE IF NOT EXISTS public.security_logs (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text not null,
  event_type text not null,
  description text,
  ip_address text,
  user_agent text,
  logged_at timestamp with time zone
);

-- Create search history table
CREATE TABLE IF NOT EXISTS public.search_history (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text not null,
  search_query text not null,
  search_type text,
  results_count integer default 0,
  searched_at timestamp with time zone
);

-- Create car sightings table
CREATE TABLE IF NOT EXISTS public.car_sightings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  car_id bigint references public.cars(id) on delete cascade not null,
  latitude decimal(10, 8) not null,
  longitude decimal(11, 8) not null,
  description text,
  sighting_date timestamp with time zone,
  verified boolean default false
);

-- Enable RLS
ALTER TABLE public.user_security ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.security_logs ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.search_history ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.car_sightings ENABLE ROW LEVEL SECURITY;

-- Policies for user_security
CREATE POLICY "Users can view their own security settings"
ON public.user_security FOR SELECT
USING (user_email = auth.jwt() ->> 'email');

CREATE POLICY "Users can update their own security settings"
ON public.user_security FOR UPDATE
USING (user_email = auth.jwt() ->> 'email');

-- Policies for security_logs
CREATE POLICY "Users can view their own security logs"
ON public.security_logs FOR SELECT
USING (user_email = auth.jwt() ->> 'email');

-- Policies for search_history
CREATE POLICY "Users can view their own search history"
ON public.search_history FOR SELECT
USING (user_email = auth.jwt() ->> 'email');

CREATE POLICY "Users can insert their search history"
ON public.search_history FOR INSERT
WITH CHECK (user_email = auth.jwt() ->> 'email');

-- Policies for car_sightings
CREATE POLICY "Anyone can view car sightings"
ON public.car_sightings FOR SELECT
USING (true);

CREATE POLICY "Anyone can add car sightings"
ON public.car_sightings FOR INSERT
WITH CHECK (true);

-- Create indexes
CREATE INDEX IF NOT EXISTS idx_user_security_email ON public.user_security(user_email);
CREATE INDEX IF NOT EXISTS idx_security_logs_user ON public.security_logs(user_email);
CREATE INDEX IF NOT EXISTS idx_security_logs_event ON public.security_logs(event_type);
CREATE INDEX IF NOT EXISTS idx_search_history_user ON public.search_history(user_email);
CREATE INDEX IF NOT EXISTS idx_car_sightings_car ON public.car_sightings(car_id);
