-- Create a table for missing cars
create table public.cars (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  make text not null,
  model text not null,
  year integer,
  color text,
  plate_number text,
  vin text, -- Vehicle Identification Number (optional but good for tracking)
  last_seen_location text,
  last_seen_lat float, -- Latitude for map
  last_seen_lng float, -- Longitude for map
  last_seen_date date,
  description text,
  contact_name text,
  contact_phone text,
  status text default 'missing' check (status in ('missing', 'found', 'stolen', 'under_investigation')),
  image_url text,
  reporter_id uuid references auth.users(id) -- if we want to track who reported it (admins)
);

-- Enable RLS (Row Level Security)
alter table public.cars enable row level security;

-- Policy: Everyone can read/view cars
create policy "Everyone can view cars" 
on public.cars for select 
using (true);

-- Policy: Only authenticated users (admins/supervisors) can insert cars
create policy "Admins can insert cars" 
on public.cars for insert 
to authenticated 
with check (true);

-- Policy: Only authenticated users (admins/supervisors) can update cars
create policy "Admins can update cars" 
on public.cars for update 
to authenticated 
using (true);

-- Policy: Only authenticated users (admins/supervisors) can delete cars
create policy "Admins can delete cars" 
on public.cars for delete 
to authenticated 
using (true);

-- Create a table for case updates (Timeline)
create table public.case_updates (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  car_id bigint references public.cars(id) on delete cascade not null,
  title text not null,
  description text,
  update_date date default CURRENT_DATE,
  update_type text check (update_type in ('info', 'sighting', 'status_change', 'official')) default 'info'
);

alter table public.case_updates enable row level security;

create policy "Everyone can view updates" on public.case_updates for select using (true);
create policy "Admins can manage updates" on public.case_updates for all to authenticated using (true);


-- Create a storage bucket for car images
insert into storage.buckets (id, name, public) 
values ('car-images', 'car-images', true);

-- Policy: Give public access to view images
create policy "Public Access" 
on storage.objects for select 
using ( bucket_id = 'car-images' );

-- Policy: Authenticated users can upload images
create policy "Auth Upload" 
on storage.objects for insert 
to authenticated 
with check ( bucket_id = 'car-images' );
