create table if not exists site_visits (
  id bigint generated by default as identity primary key,
  visited_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table site_visits enable row level security;

create policy "Anyone can insert visits"
  on site_visits for insert
  with check (true);

create policy "Admins can view visits"
  on site_visits for select
  using (true); -- Ideally restrict to admins, but open for now for simplicity in dashboard fetching
