CREATE TABLE IF NOT EXISTS public.car_images (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  car_id bigint references public.cars(id) on delete cascade,
  image_url text not null,
  image_type text default 'unknown' check (image_type in ('front', 'back', 'side', 'interior', 'damage', 'general')),
  uploader_email text,
  is_verified boolean default false,
  processing_status text default 'pending' check (processing_status in ('pending', 'processing', 'completed', 'failed')),
  ai_confidence float,
  detected_features jsonb,
  color text,
  damage_detected boolean default false,
  damage_description text,
  is_primary boolean default false
);

CREATE TABLE IF NOT EXISTS public.visual_recognition_matches (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  source_image_id bigint references public.car_images(id) on delete cascade not null,
  matched_car_id bigint references public.cars(id) on delete cascade not null,
  matched_image_id bigint references public.car_images(id) on delete cascade,
  similarity_score float check (similarity_score >= 0 and similarity_score <= 100) not null,
  match_type text default 'similar' check (match_type in ('exact', 'very_similar', 'similar', 'possible')),
  ai_model text,
  processing_time_ms integer,
  is_verified boolean default false,
  verification_note text,
  user_feedback text check (user_feedback in ('correct', 'incorrect', 'maybe'))
);

CREATE TABLE IF NOT EXISTS public.extracted_car_details (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  image_id bigint references public.car_images(id) on delete cascade not null,
  make text,
  model text,
  year integer,
  color text,
  body_type text,
  license_plate text,
  features text[],
  confidence_scores jsonb,
  extraction_method text default 'ai' check (extraction_method in ('ai', 'manual', 'hybrid')),
  is_accurate boolean default false
);

CREATE TABLE IF NOT EXISTS public.visual_search_results (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  user_email text,
  uploaded_image_url text not null,
  search_filters jsonb,
  total_matches integer,
  top_match_car_id bigint references public.cars(id) on delete set null,
  top_match_score float,
  search_completed_at timestamp with time zone,
  user_selected_car_id bigint references public.cars(id) on delete set null,
  is_useful boolean
);

CREATE TABLE IF NOT EXISTS public.ai_model_performance (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  model_name text not null,
  model_version text,
  total_images_processed integer default 0,
  successful_detections integer default 0,
  failed_detections integer default 0,
  average_confidence float,
  accuracy_rate float,
  last_updated timestamp with time zone
);

ALTER TABLE public.car_images enable row level security;
ALTER TABLE public.visual_recognition_matches enable row level security;
ALTER TABLE public.extracted_car_details enable row level security;
ALTER TABLE public.visual_search_results enable row level security;
ALTER TABLE public.ai_model_performance enable row level security;

CREATE POLICY "Everyone can view car images"
ON public.car_images for select
USING (true);

CREATE POLICY "Users can upload images"
ON public.car_images for insert
WITH CHECK (true);

CREATE POLICY "Image owners can update images"
ON public.car_images for update
USING (uploader_email = auth.jwt() ->> 'email' OR true);

CREATE POLICY "Everyone can view matches"
ON public.visual_recognition_matches for select
USING (true);

CREATE POLICY "System can insert matches"
ON public.visual_recognition_matches for insert
WITH CHECK (true);

CREATE POLICY "Everyone can view extracted details"
ON public.extracted_car_details for select
USING (true);

CREATE POLICY "System can insert details"
ON public.extracted_car_details for insert
WITH CHECK (true);

CREATE POLICY "Users can view search results"
ON public.visual_search_results for select
USING (user_email = auth.jwt() ->> 'email' OR true);

CREATE POLICY "Users can insert search"
ON public.visual_search_results for insert
WITH CHECK (true);

CREATE POLICY "Admins can view AI performance"
ON public.ai_model_performance for select
USING (true);

CREATE POLICY "System can update performance"
ON public.ai_model_performance for update
USING (true);

CREATE INDEX IF NOT EXISTS idx_car_images_car_id ON public.car_images(car_id);
CREATE INDEX IF NOT EXISTS idx_car_images_processing_status ON public.car_images(processing_status);
CREATE INDEX IF NOT EXISTS idx_car_images_is_primary ON public.car_images(is_primary);
CREATE INDEX IF NOT EXISTS idx_visual_recognition_matches_source ON public.visual_recognition_matches(source_image_id);
CREATE INDEX IF NOT EXISTS idx_visual_recognition_matches_matched_car ON public.visual_recognition_matches(matched_car_id);
CREATE INDEX IF NOT EXISTS idx_visual_recognition_matches_score ON public.visual_recognition_matches(similarity_score);
CREATE INDEX IF NOT EXISTS idx_extracted_car_details_image_id ON public.extracted_car_details(image_id);
CREATE INDEX IF NOT EXISTS idx_extracted_car_details_make_model ON public.extracted_car_details(make, model);
CREATE INDEX IF NOT EXISTS idx_visual_search_results_user_email ON public.visual_search_results(user_email);
CREATE INDEX IF NOT EXISTS idx_ai_model_performance_name ON public.ai_model_performance(model_name);
