-- Create witnesses/contributors table
CREATE TABLE IF NOT EXISTS public.witnesses (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  email text,
  phone text,
  name text,
  credibility_score integer default 0,
  total_contributions integer default 0,
  helpful_reports integer default 0,
  false_reports integer default 0,
  reputation_badge text default 'bronze' check (reputation_badge in ('bronze', 'silver', 'gold', 'platinum')),
  is_verified boolean default false,
  is_banned boolean default false,
  last_contribution timestamp with time zone
);

-- Create witness ratings table
CREATE TABLE IF NOT EXISTS public.witness_ratings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  witness_id bigint references public.witnesses(id) on delete cascade not null,
  car_id bigint references public.cars(id) on delete cascade,
  rater_email text,
  rating integer check (rating >= 1 and rating <= 5),
  feedback text,
  is_helpful boolean,
  report_status text check (report_status in ('useful', 'not_useful', 'false_alarm', 'verified'))
);

-- Create contributions table (sightings/tips submitted by witnesses)
CREATE TABLE IF NOT EXISTS public.witness_contributions (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  witness_id bigint references public.witnesses(id) on delete cascade,
  car_id bigint references public.cars(id) on delete cascade not null,
  contribution_type text check (contribution_type in ('sighting', 'tip', 'location', 'information')) default 'tip',
  title text not null,
  description text,
  location text,
  latitude float,
  longitude float,
  report_date date,
  status text default 'pending' check (status in ('pending', 'verified', 'false_alarm', 'helpful', 'not_helpful')),
  image_url text,
  is_anonymous boolean default false,
  verification_count integer default 0
);

-- Enable RLS
ALTER TABLE public.witnesses enable row level security;
ALTER TABLE public.witness_ratings enable row level security;
ALTER TABLE public.witness_contributions enable row level security;

-- Policies for witnesses
CREATE POLICY "Everyone can view witnesses" 
ON public.witnesses for select 
USING (true);

CREATE POLICY "Users can insert witness" 
ON public.witnesses for insert 
WITH CHECK (true);

CREATE POLICY "Admins can update witness" 
ON public.witnesses for update 
to authenticated 
USING (true);

-- Policies for ratings
CREATE POLICY "Everyone can view ratings" 
ON public.witness_ratings for select 
USING (true);

CREATE POLICY "Anyone can rate witness" 
ON public.witness_ratings for insert 
WITH CHECK (true);

CREATE POLICY "Admins can manage ratings" 
ON public.witness_ratings for update 
to authenticated 
USING (true);

-- Policies for contributions
CREATE POLICY "Everyone can view contributions" 
ON public.witness_contributions for select 
USING (true);

CREATE POLICY "Anyone can contribute" 
ON public.witness_contributions for insert 
WITH CHECK (true);

CREATE POLICY "Admins can manage contributions" 
ON public.witness_contributions for update 
to authenticated 
USING (true);

-- Indexes for performance
CREATE INDEX IF NOT EXISTS idx_witnesses_email ON public.witnesses(email);
CREATE INDEX IF NOT EXISTS idx_witnesses_credibility ON public.witnesses(credibility_score DESC);
CREATE INDEX IF NOT EXISTS idx_witness_ratings_witness_id ON public.witness_ratings(witness_id);
CREATE INDEX IF NOT EXISTS idx_witness_contributions_car_id ON public.witness_contributions(car_id);
CREATE INDEX IF NOT EXISTS idx_witness_contributions_witness_id ON public.witness_contributions(witness_id);
